DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Card;

CREATE TABLE IF NOT EXISTS User (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  pseudo TEXT NOT NULL UNIQUE,
  email TEXT NOT NULL UNIQUE,
  mot_de_passe TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Card (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  question TEXT NOT NULL UNIQUE,
  reponse TEXT NOT NULL,
  thematique TEXT NOT NULL
);